services:
    # sftp server
    server-sftp:
        image: atmoz/sftp:latest
        container_name: server-sftp
        ports:
            - "${ENV_DEV_SFTP_PORT}:22"
        command: ${ENV_DEV_SFTP_USER}:${ENV_DEV_SFTP_PASSWORD}:::../${ENV_DEV_SFTP_USER}
        volumes:
            - ../server_sftp:${ENV_DEV_SFTP_CONTAINER_PATH_FOLDER}
        networks:
            - net-dev-data-street

networks:
    net-dev-data-street:
        name: net-dev-data-street
        external: true
